added workflows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,16 +1,20 @@
-name: test
+name: Test
 
-on: workflow_dispatch
+on:
+  pull_request:
+    branches:
+      - master
+  workflow_dispatch:
 
 env:
   FOUNDRY_PROFILE: ci
 
 jobs:
-  check:
+  check-test:
     strategy:
       fail-fast: true
 
-    name: Foundry project
+    name: Forge Project
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -32,3 +36,32 @@ jobs:
         run: |
           forge test -vvv
         id: test
+  
+  check-template:
+    name: Check Template
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: recursive
+      
+      - name: Check Template
+        run: |
+          # Store the current commit hash
+          CURRENT_COMMIT=$(git rev-parse HEAD)
+          
+          # Perform the sync
+          make sync
+          
+          # Get the new commit hash after sync
+          NEW_COMMIT=$(git rev-parse HEAD)
+          
+          # Compare the commit hashes
+          if [ "$CURRENT_COMMIT" != "$NEW_COMMIT" ]; then
+            echo "Error: The repository is not up to date with the template."
+            echo "Please sync with the template and commit the changes before proceeding."
+            exit 1
+          fi
+          
+          echo "Repository is up to date with the template."
+
